/**
 * Created by andrew.larsen on 1/22/2016.
 */
(function()
 {
	var angularApp = angular.module("loginViewer", ['ngMaterial']);
	//Controller class for login functionality
	var LoginController = function ($scope, $http,$location) {
		/**
         * Method to store auth token
         * @param response
         */
		var onSuccess = function(response){
			app.showAlert("Login Successful!", '')
			storeToken(response.data);

		};
		/**
         * Method to handle error from login method
         * @param error
         */
		var onError = function(error){
			app.showAlert("Failed to load server data",error)
		};
		/**
         * Method to submit login request to Login API
         * Will return an auth token generated by the server
         * @param userName
         * @param password
         */
		$scope.login = function(userName, password) {
			//submit post
			$http.post(
				JSON.parse(localStorage.OPENSHIFT).URLS.LOGIN,
				{
					userName: userName, password: password
				}
			).then(onSuccess, onError)
		};
		$scope.test = function(){
			$http.post(
				JSON.parse(localStorage.OPENSHIFT).URLS.HELLO_WORLD,
				{
					headers: {'x-access-token': localStorage.token}
				}).then(onSuccess,onError)
		};
		$scope.helloLocation = function(){
			navigator.geolocation.getCurrentPosition(function(position)
													 {
				// just to show how to access latitute and longitude
				var location = [position.coords.latitude, position.coords.longitude];
				alert(location)
			},
													 function(error)
													 {
				// error getting GPS coordinates
				alert('code: ' + error.code + ' with message: ' + error.message + '\n');
			},
													 { enableHighAccuracy: true, maximumAge: 0, timeout: 10000 });
		}
		/**
         * Method to store token data
         * @param data
         */
		var storeToken = function(data){
			//for now lets just store the tokens
			localStorage.token = data.token;
			localStorage.expires = parseInt(data.expires);
		}
		};

	var LeftMenuController = function ($scope, $timeout, $mdSidenav, $log) {
		$scope.close = function () {
			$mdSidenav('left').close()
				.then(function () {
				$log.debug("close LEFT is done");
			});
		};
	};

	var MenuController = function ($scope, $timeout, $mdSidenav, $log) {
		$scope.toggleLeft = buildDelayedToggler('left');
		$scope.toggleRight = buildToggler('right');
		$scope.isOpenRight = function(){
			return $mdSidenav('right').isOpen();
		};
		/**
     * Supplies a function that will continue to operate until the
     * time is up.
     */
		function debounce(func, wait, context) {
			var timer;
			return function debounced() {
				var context = $scope,
					args = Array.prototype.slice.call(arguments);
				$timeout.cancel(timer);
				timer = $timeout(function() {
					timer = undefined;
					func.apply(context, args);
				}, wait || 10);
			};
		}
		/**
     * Build handler to open/close a SideNav; when animation finishes
     * report completion in console
     */
		function buildDelayedToggler(navID) {
			return debounce(function() {
				$mdSidenav(navID)
					.toggle()
					.then(function () {
					$log.debug("toggle " + navID + " is done");
				});
			}, 200);
		}
		function buildToggler(navID) {
			return function() {
				$mdSidenav(navID)
					.toggle()
					.then(function () {
					$log.debug("toggle " + navID + " is done");
				});
			}
		}
	};

	angularApp.controller("LoginController", ["$scope","$http",LoginController])
	angularApp.controller("LeftMenuController", ["$scope", "$http", "$mdSidenav", "$log", LeftMenuController])
	angularApp.controller("MenuController", ["$scope", "$http", "$mdSidenav", "$log", MenuController])

}());